#!/bin/bash
"""
Fernando Platform Proxy Integration Setup Script

This script completes the setup of all proxy services to ensure zero API key exposure
while maintaining full functionality of the platform.

Usage:
    ./setup_proxy_integration.sh [--production] [--validate-only] [--monitor]
"""

import os
import sys
import subprocess
import asyncio
import json
import logging
from pathlib import Path
from typing import Dict, Any, List
import time

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent))

from deploy_all_proxies import ProxyServerManager
from monitor_proxy_services import ProxyServiceMonitor
from validate_proxy_integration import ProxyIntegrationValidator

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class ProxyIntegrationSetup:
    """Complete proxy integration setup and deployment"""
    
    def __init__(self, production: bool = False):
        self.production = production
        self.setup_results = {
            "timestamp": time.time(),
            "environment": "production" if production else "development",
            "steps_completed": [],
            "steps_failed": [],
            "warnings": [],
            "recommendations": []
        }
    
    async def run_complete_setup(self) -> Dict[str, Any]:
        """Run complete proxy integration setup"""
        logger.info("🚀 Starting complete proxy integration setup...")
        
        start_time = time.time()
        
        try:
            # Step 1: Setup environment configuration
            await self._setup_environment()
            
            # Step 2: Deploy proxy servers
            await self._deploy_proxy_servers()
            
            # Step 3: Validate integration
            await self._validate_integration()
            
            # Step 4: Setup monitoring
            await self._setup_monitoring()
            
            # Step 5: Generate deployment report
            await self._generate_deployment_report()
            
            self.setup_results["duration"] = time.time() - start_time
            
            # Print final summary
            await self._print_summary()
            
            return self.setup_results
            
        except Exception as e:
            logger.error(f"Setup failed: {e}")
            self.setup_results["steps_failed"].append(f"Setup failed: {e}")
            return self.setup_results
    
    async def _setup_environment(self):
        """Setup environment configuration"""
        logger.info("⚙️ Setting up environment configuration...")
        
        try:
            # Create .env file if it doesn't exist
            env_file = Path("/workspace/fernando/backend/.env")
            if not env_file.exists():
                env_example = Path("/workspace/fernando/backend/.env.example")
                if env_example.exists():
                    env_example.copy(env_file)
                    self.setup_results["steps_completed"].append("Created .env from example")
                else:
                    # Create basic .env file
                    await self._create_basic_env_file()
                    self.setup_results["steps_completed"].append("Created basic .env file")
            else:
                self.setup_results["steps_completed"].append("Environment file already exists")
            
            # Load environment variables
            self._load_environment_variables()
            
            # Validate required environment variables
            self._validate_environment_variables()
            
        except Exception as e:
            self.setup_results["steps_failed"].append(f"Environment setup failed: {e}")
            raise
    
    async def _create_basic_env_file(self):
        """Create basic environment file"""
        env_content = """# Fernando Platform Environment Configuration
# Generated by proxy integration setup

# Proxy Configuration
PROXY_ENABLED=true
PROXY_FALLBACK_ENABLED=true
PROXY_TIMEOUT=30
PROXY_MAX_RETRIES=3

# Service Endpoints (Development)
LLM_PROXY_ENDPOINT=http://localhost:8000
OCR_PROXY_ENDPOINT=http://localhost:8001
TOCONLINE_PROXY_ENDPOINT=http://localhost:8002
STRIPE_PROXY_ENDPOINT=http://localhost:8003
PAYPAL_PROXY_ENDPOINT=http://localhost:8004
COINBASE_PROXY_ENDPOINT=http://localhost:8005
OPENAI_PROXY_ENDPOINT=http://localhost:8006

# Security
PROXY_ENCRYPTION_ENABLED=true
CIRCUIT_BREAKER_ENABLED=true

# Development
DEV_MODE=true
"""
        
        env_file = Path("/workspace/fernando/backend/.env")
        with open(env_file, 'w') as f:
            f.write(env_content)
    
    def _load_environment_variables(self):
        """Load environment variables from .env file"""
        env_file = Path("/workspace/fernando/backend/.env")
        if env_file.exists():
            with open(env_file, 'r') as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith('#') and '=' in line:
                        key, value = line.split('=', 1)
                        if key not in os.environ:
                            os.environ[key] = value
        else:
            logger.warning("No .env file found")
    
    def _validate_environment_variables(self):
        """Validate required environment variables"""
        required_vars = [
            "PROXY_ENABLED",
            "LLM_PROXY_ENDPOINT",
            "OCR_PROXY_ENDPOINT",
            "STRIPE_PROXY_ENDPOINT",
            "PAYPAL_PROXY_ENDPOINT",
            "COINBASE_PROXY_ENDPOINT"
        ]
        
        missing_vars = []
        for var in required_vars:
            if not os.getenv(var):
                missing_vars.append(var)
        
        if missing_vars:
            self.setup_results["warnings"].append(f"Missing environment variables: {missing_vars}")
        else:
            self.setup_results["steps_completed"].append("Environment variables validated")
    
    async def _deploy_proxy_servers(self):
        """Deploy proxy servers"""
        logger.info("🚀 Deploying proxy servers...")
        
        try:
            manager = ProxyServerManager(production=self.production)
            
            # Deploy all servers
            deployment_results = await manager.deploy_all_servers()
            
            # Check deployment status
            healthy_servers = sum(1 for health in deployment_results["health_checks"].values() 
                                 if health["status"] == "healthy")
            total_servers = len(deployment_results["health_checks"])
            
            if healthy_servers == total_servers:
                self.setup_results["steps_completed"].append(f"All {total_servers} proxy servers deployed successfully")
            elif healthy_servers > 0:
                self.setup_results["warnings"].append(f"Only {healthy_servers}/{total_servers} servers are healthy")
            else:
                self.setup_results["steps_failed"].append("No proxy servers are healthy")
            
            # Store deployment results
            self.setup_results["deployment_results"] = deployment_results
            
        except Exception as e:
            self.setup_results["steps_failed"].append(f"Proxy server deployment failed: {e}")
            raise
    
    async def _validate_integration(self):
        """Validate proxy integration"""
        logger.info("🔍 Validating proxy integration...")
        
        try:
            validator = ProxyIntegrationValidator()
            validation_results = await validator.run_comprehensive_validation()
            
            # Check validation results
            if len(validation_results["errors"]) == 0:
                self.setup_results["steps_completed"].append("Proxy integration validation passed")
            else:
                self.setup_results["steps_failed"].append(f"Validation failed with {len(validation_results['errors'])} errors")
            
            # Store validation results
            self.setup_results["validation_results"] = validation_results
            
        except Exception as e:
            self.setup_results["steps_failed"].append(f"Integration validation failed: {e}")
            raise
    
    async def _setup_monitoring(self):
        """Setup monitoring and health checks"""
        logger.info("📊 Setting up monitoring...")
        
        try:
            monitor = ProxyServiceMonitor()
            
            # Run initial health check
            health_report = await monitor.run_comprehensive_health_check()
            
            if health_report.healthy_services == health_report.total_services:
                self.setup_results["steps_completed"].append("Monitoring setup successful - all services healthy")
            else:
                self.setup_results["warnings"].append(f"Monitoring setup complete - {health_report.unhealthy_services} services unhealthy")
            
            # Store monitoring results
            self.setup_results["monitoring_results"] = {
                "healthy_services": health_report.healthy_services,
                "total_services": health_report.total_services,
                "report_file": "reports/proxy_health_report_latest.json"
            }
            
        except Exception as e:
            self.setup_results["steps_failed"].append(f"Monitoring setup failed: {e}")
            raise
    
    async def _generate_deployment_report(self):
        """Generate comprehensive deployment report"""
        logger.info("📄 Generating deployment report...")
        
        try:
            report = {
                "setup_summary": self.setup_results,
                "deployment_timestamp": time.time(),
                "environment": "production" if self.production else "development",
                "status": "success" if not self.setup_results["steps_failed"] else "partial_success",
                "next_steps": [
                    "Configure production API keys on proxy servers",
                    "Set up monitoring and alerting",
                    "Test all functionality in production environment",
                    "Update DNS/routes to proxy servers",
                    "Monitor performance and health"
                ]
            }
            
            # Save report
            report_file = Path("/workspace/fernando/backend/proxy_deployment_summary.json")
            with open(report_file, 'w') as f:
                json.dump(report, f, indent=2)
            
            # Also create markdown report
            await self._create_markdown_report(report)
            
            self.setup_results["steps_completed"].append(f"Deployment report saved to {report_file}")
            
        except Exception as e:
            self.setup_results["steps_failed"].append(f"Report generation failed: {e}")
    
    async def _create_markdown_report(self, report: Dict[str, Any]):
        """Create markdown deployment report"""
        lines = [
            "# Fernando Platform Proxy Integration - Deployment Report",
            "",
            f"**Deployment Date:** {time.strftime('%Y-%m-%d %H:%M:%S')}",
            f"**Environment:** {report['environment'].title()}",
            f"**Status:** {report['status'].replace('_', ' ').title()}",
            "",
            "## Setup Summary",
            "",
            f"- **Duration:** {self.setup_results['duration']:.2f} seconds",
            f"- **Steps Completed:** {len(self.setup_results['steps_completed'])}",
            f"- **Steps Failed:** {len(self.setup_results['steps_failed'])}",
            f"- **Warnings:** {len(self.setup_results['warnings'])}",
            "",
            "## Completed Steps",
            ""
        ]
        
        for step in self.setup_results["steps_completed"]:
            lines.append(f"✅ {step}")
        
        if self.setup_results["steps_failed"]:
            lines.extend([
                "",
                "## Failed Steps",
                ""
            ])
            for step in self.setup_results["steps_failed"]:
                lines.append(f"❌ {step}")
        
        if self.setup_results["warnings"]:
            lines.extend([
                "",
                "## Warnings",
                ""
            ])
            for warning in self.setup_results["warnings"]:
                lines.append(f"⚠️ {warning}")
        
        # Add deployment details if available
        if "deployment_results" in self.setup_results:
            dep_results = self.setup_results["deployment_results"]
            lines.extend([
                "",
                "## Deployment Details",
                "",
                f"- **Total Servers:** {dep_results.get('total_servers', 0)}",
                f"- **Deployment Duration:** {dep_results.get('deployment_duration', 0):.2f}s"
            ])
        
        lines.extend([
            "",
            "## Next Steps",
            ""
        ])
        
        for step in report["next_steps"]:
            lines.append(f"1. {step}")
        
        lines.extend([
            "",
            "## Configuration",
            "",
            "### Environment Variables",
            "",
            "```bash",
            "# Proxy Configuration",
            "PROXY_ENABLED=true",
            "PROXY_FALLBACK_ENABLED=true",
            "",
            "# Service Endpoints",
            "LLM_PROXY_ENDPOINT=http://localhost:8000",
            "OCR_PROXY_ENDPOINT=http://localhost:8001",
            "STRIPE_PROXY_ENDPOINT=http://localhost:8003",
            "PAYPAL_PROXY_ENDPOINT=http://localhost:8004",
            "COINBASE_PROXY_ENDPOINT=http://localhost:8005",
            "```",
            "",
            "## Security Benefits",
            "",
            "✅ **Zero API Key Exposure** - All API keys are now managed server-side",
            "✅ **Enhanced Security** - Centralized authentication and authorization",
            "✅ **Improved Monitoring** - Comprehensive request/response telemetry",
            "✅ **Better Resilience** - Circuit breaker and fallback mechanisms",
            "✅ **Scalability** - Centralized API management and load balancing",
            "",
            "---\n",
            "*This report was generated by the Fernando Platform Proxy Integration Setup Script*"
        ])
        
        # Save markdown report
        md_report_file = Path("/workspace/fernando/backend/PROXY_INTEGRATION_DEPLOYMENT_REPORT.md")
        with open(md_report_file, 'w') as f:
            f.write('\n'.join(lines))
    
    async def _print_summary(self):
        """Print final setup summary"""
        print("\n" + "="*60)
        print("🚀 PROXY INTEGRATION SETUP COMPLETE")
        print("="*60)
        
        print(f"\n📊 Setup Summary:")
        print(f"   Duration: {self.setup_results['duration']:.2f} seconds")
        print(f"   Steps Completed: {len(self.setup_results['steps_completed'])}")
        print(f"   Steps Failed: {len(self.setup_results['steps_failed'])}")
        print(f"   Warnings: {len(self.setup_results['warnings'])}")
        
        print(f"\n✅ Completed Steps:")
        for step in self.setup_results["steps_completed"]:
            print(f"   • {step}")
        
        if self.setup_results["steps_failed"]:
            print(f"\n❌ Failed Steps:")
            for step in self.setup_results["steps_failed"]:
                print(f"   • {step}")
        
        if self.setup_results["warnings"]:
            print(f"\n⚠️ Warnings:")
            for warning in self.setup_results["warnings"]:
                print(f"   • {warning}")
        
        print(f"\n🎉 Proxy Integration Status:")
        if not self.setup_results["steps_failed"]:
            print("   ✅ Ready for production deployment")
            print("   ✅ Zero API key exposure achieved")
            print("   ✅ All services integrated with proxy")
        else:
            print("   ⚠️  Setup completed with issues")
            print("   ⚠️  Review failed steps before production deployment")
        
        print(f"\n📄 Reports generated:")
        print("   • /workspace/fernando/backend/proxy_deployment_summary.json")
        print("   • /workspace/fernando/backend/PROXY_INTEGRATION_DEPLOYMENT_REPORT.md")
        
        print(f"\n🔗 Useful Commands:")
        print("   • Monitor health: python monitor_proxy_services.py --detailed")
        print("   • Validate integration: python validate_proxy_integration.py --detailed")
        print("   • Deploy servers: python deploy_all_proxies.py")


async def main():
    """Main setup function"""
    import argparse
    
    parser = argparse.ArgumentParser(description="Setup Fernando platform proxy integration")
    parser.add_argument("--production", action="store_true", help="Deploy in production mode")
    parser.add_argument("--validate-only", action="store_true", help="Only run validation")
    parser.add_argument("--monitor", action="store_true", help="Setup monitoring only")
    
    args = parser.parse_args()
    
    setup = ProxyIntegrationSetup(production=args.production)
    
    try:
        if args.validate_only:
            # Just run validation
            validator = ProxyIntegrationValidator()
            results = await validator.run_comprehensive_validation()
            print(json.dumps(results, indent=2))
        elif args.monitor:
            # Just setup monitoring
            monitor = ProxyServiceMonitor()
            health_report = await monitor.run_comprehensive_health_check()
            print(f"Monitoring setup complete. {health_report.healthy_services}/{health_report.total_services} services healthy")
        else:
            # Run complete setup
            results = await setup.run_complete_setup()
            
            # Exit with appropriate code
            if results["steps_failed"]:
                sys.exit(1)
            else:
                sys.exit(0)
                
    except KeyboardInterrupt:
        print("\n🛑 Setup interrupted by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Setup failed: {e}")
        sys.exit(1)


if __name__ == "__main__":
    asyncio.run(main())